version: '3.8'

services:
  redis:
    image: redis:6
  web:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
#    command: python manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 -t 300 chat.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

